### PR TITLE
Reduce number of certificate requests

### PR DESCRIPTION
**Pull request by davidkuridza**
Everytime signature keys were needed, an HTTP request was made to the
certificate endpoint, resulting in at least three identical requests
made to the certification server. This behaviour has been improved by
adding a simple in-request caching, reducing the amount of requests to
just one.

At the same time minor data validation has been added as well.

### CODE REVIEW

**Comment by stepicm** [comment]
:+1:

**Comment by SamoB25** [comment]
:+1:

**Comment by TimPapler** [comment]
👍

**Comment by dominikznidar** [comment]
I remember @stepicm mentioning this was fetched 6 times on each request. Does this mean you'll still be validating the same token 6 times? One validation takes about 15ms of CPU crunching. Might be worth to tackle the issue there.

**Comment by davidkuridza** [comment]
@dominikznidar Did not know about it, will look into it a bit later if that's OK. Can this one be merged?

**Comment by dominikznidar** [comment]
:+

**Pull request merged**
